spring:
  application:
    name: eureka-customer
eureka:
  client:
    service-url:
      defaultZone: http://peer1:9001/eureka/,http://peer2:9002/eureka/,http://peer3:9003/eureka/
server:
  port: 9006