
server:
  port: 9002
spring:
  application:
    name: eureka-service
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:9001/eureka/,http://peer3:9003/eureka/
    fetch-registry: true
    register-with-eureka: true
